### PR TITLE
updated Kotlin to 1.5.0, Android SDK/Gradle Plugin, dependencies, Gradle wrapper

### PR DESCRIPTION
**Pull request by suntrix**

### CODE REVIEW

**Comment by suntrix** [comment]
@nbransby Can you guys fix the JS tests? They're failing very often for no particular reason.

**Review by julianfalcionelli — APPROVED** [review]

**Comment by nbransby** [comment]
@suntrix JS tests passing now, seems android test are failing now - guess its todo with the upgrade to 1.5:
`No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).`

**Comment by suntrix** [comment]
> @suntrix JS tests passing now, seems android test are failing now - guess its todo with the upgrade to 1.5:
> `No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).`

Thanks! I'll check those ASAP.

**Comment by suntrix** [comment]
Closing in favour of https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/189

**Pull request closed without merging**
