### PR TITLE
Bumped dependencies and Gradle wrapper

### PR DESCRIPTION
**Pull request by siarhei-luskanau**

### CODE REVIEW

**Comment by nbransby** [comment]
@siarhei-luskanau would you like to also add [this](https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/578) to this PR?

**Comment by siarhei-luskanau** [comment]
> @siarhei-luskanau would you like to also add [this](https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/578) to this PR?

@nbransby  I have the issue with updating the `"firebase-cocoapods = "11.1.0"`. Let we update it in separate PR?

**Comment by nbransby** [comment]
Sure, what is the issue?

**Comment by siarhei-luskanau** [comment]
`:firebase-auth:iosX64Test` and `:firebase-firestore:iosX64Test` are failing: https://github.com/GitLiveApp/firebase-kotlin-sdk/actions/runs/10570216015

**Review by nbransby — APPROVED** [review]

**Pull request merged**
