### PR TITLE
Implement Firebase remote config API

### LINKED ISSUE #134: Add implementation for remote-config
| Library               | Class                            | Platforms                  |
| :-----------------| :------------------------ | :---------------------- |
| remote-config | RemoteConfig | Android, iOS, js  |

Create implementation for a shared version of Firebase Remote Config.

### LINKED ISSUE #172: Firebase Config
Please implement multiplatform firebase config.

### PR DESCRIPTION
**Pull request by shepeliev**
Closes #134 
Closes #172

### CODE REVIEW

**Comment by nbransby** [comment]
Hey thanks @shepeliev this looks great! Couple of suggestions:
- We try and match the [android ktx library ap](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/remoteconfig/ktx/package-summary?hl=en&authuser=0)i as closely as possible:
- For example you should remove getValue from the FirebaseRemoteConfig and just replace with the [operator version](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/remoteconfig/ktx/package-summary?hl=en&authuser=0#get ) that the kotlin extensions adds

**Comment by shepeliev** [comment]
> Hey thanks @shepeliev this looks great! Couple of suggestions:
> 
> * We try and match the [android ktx library ap](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/remoteconfig/ktx/package-summary?hl=en&authuser=0)i as closely as possible:
> * For example you should remove getValue from the FirebaseRemoteConfig and just replace with the [operator version](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/remoteconfig/ktx/package-summary?hl=en&authuser=0#get) that the kotlin extensions adds

Thanks for reviewing. Yes, it makes sense. I'll rework it soon.

**Comment by nbransby** [comment]
Actually why dont we go one step further and use a reified type param to also replace all the `get*Type*` methods, e.g:

```
    inline operator fun <reified T> get(key: String): T = when(T::class) {
        String::class -> android.getString(key)
        FirebaseRemoteConfigValue::class -> android.getValue(key)
        ...
        else -> throw IllegalArgumentException()
    } as T
```

**Comment by shepeliev** [comment]
> Actually why dont we go one step further and use a reified type param to also replace all the `get*Type*` methods, e.g:
> 
> ```
>     inline operator fun <reified T> get(key: String): T = when(T::class) {
>         String::class -> android.getString(key)
>         FirebaseRemoteConfigValue::class -> android.getValue(key)
>         ...
>         else -> throw IllegalArgumentException()
>     } as T
> ```

That looks great. Just pushed an update.

**Comment by suntrix** [comment]
@nbransby any ideas when this will be merged?

**Comment by Reedyuk** [comment]
@shepeliev - is it possible to rename it? Google refers to theirs as the project being called firebase-config and their imports are Firebase.remoteConfig(you have done the import object right, its just the name of the project/directories that needs changing).

**Comment by Reedyuk** [comment]
Rest looks great!

**Comment by shepeliev** [comment]
> @shepeliev - is it possible to rename it? Google refers to theirs as the project being called firebase-config and their imports are Firebase.remoteConfig(you have done the import object right, its just the name of the project/directories that needs changing).

Yep, you are right about naming the project. I think I'll do it in a couple of hours tonight.

**Review by Reedyuk — APPROVED** [review]

**Pull request merged**
