### PR TITLE
updated dependencies & Kotlin 1.6.21

### PR DESCRIPTION
**Pull request by suntrix**

### CODE REVIEW

**Comment by nbransby** [comment]
I noticed the build is failing on this, any ideas why?

**Comment by suntrix** [comment]
Not sure yet, but I'll try to fix it this week.

**Comment by suntrix** [comment]
Looks like the issue is somehow connected with Kotlin 1.6.21, updating to 1.7.x fixes it.
I'll create a new PR with Kotlin 1.7.10 update & close this one.

Users that use Kotlin 1.6.21 in their projects will still be able to use the last release that was build with Kotlin 1.6.10.

**Comment by suntrix** [comment]
https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/337

**Pull request closed without merging**
