### PR TITLE
Moves ValueWithSerializer back into public API

### PR DESCRIPTION
**Pull request by Daeda88**
It had become part of commons-internal which kind of defeats the purpose.

Also made FirebaseEncoder/FirebaseDecoder an interface in the public API. Useful for writing custom Serializers that have custom behaviour on Firebase

### CODE REVIEW

**Comment by nbransby** [comment]
> It had become part of commons-internal which kind of defeats the purpose.

I'm going to need more of an explanation, is it to fix this issue https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/590 ?

**Comment by Daeda88** [comment]
No I actually ran into it myself. The ValueWithSerializer class was originally in the regular commons library and allows encoding a value when dealing with File paths. But it's no longer accessible so I moved it back. Though I'm not entirely sure if this was introduced by Splendo or GitLive. Technically you can achieve the same behavior with a custom SerializerModule though, this does add some convenience

**Comment by nbransby** [comment]
> allows encoding a value when dealing with File paths

Could you give a code example of what you mean? A search of ValueWithSerializer in the README doesn't return any results.

**Comment by mr-kew** [comment]
@Daeda88 Does this somehow relate to [#604](https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/604)?

**Comment by Daeda88** [comment]
Dropping in favour of #607

**Pull request closed without merging**
