### PR TITLE
Upgrade to Kotlin 1.9.20 & gradle 8

### PR DESCRIPTION
**Pull request by Daeda88**
This updates the gradle build tools to Gradle 8, moves to Kotlin 1.8.21, coroutines 1.7.1 and cleans up the build stack

- [x] Moves build to Gradle 8
- [x] Upgrade kotlin versions to 1.8.21, coroutines 1.7.1, serialization to 1.5.1
- [x] Upgrades firebase to 32..0.0 (android) and 10.9.0 (iOS)
- [x] Use Android Source Layout V2
- [x] Use version variables in gradle.properties to ease future upgrades

### CODE REVIEW

**Comment by Daeda88** [comment]
Once this is merged, I can make a few more PRs from our Splendo fork, including fixes to Polymorphic serialization (it fails for nesting, doesnt support non-sealed polymorphism etc), several iOS methods, and tracking the new firestore persistence settings

**Comment by nbransby** [comment]
Another huge PR 🙄 

What are the podspecs for?

**Comment by Daeda88** [comment]
> Another huge PR 🙄
> 
> What are the podspecs for?

To get them to build. Im guessing the latest plugin requires them (which is a bit weird since we set noPodspec which implies you shouldnt need them). But this is on the native plugin side.

And yeah, its kind of big because the new Android filestructure requires renames from androidAndroidTest to androidInstrumentedTest etc. But the old way will get deprecated so you'll have to do the renames eventually.

**Comment by nbransby** [comment]
> And yeah, its kind of big because the new Android filestructure requires renames from androidAndroidTest to androidInstrumentedTest etc. But the old way will get deprecated so you'll have to do the renames eventually.

This PR includes upgrading kotlin.mpp.androidSourceSetLayoutVersion to 2? That's great as it was on our todo list but it would be super helpful if that was in the PR title of description somewhere. In fact this task alone would make a sizable PR and should really be submitted separately, that would really help us improve our TTM (time to merge) on this project 🙏

**Comment by Daeda88** [comment]
@nbransby I dont think it would reduce the size that much. Upgrading to Gradle 8 means that Android now needs the namespace set. As a result, the cleanup requires most Manifest files to be deleted. With 10 modules, that just adds up. Most of the files changed dont contain that much, except for the Build.gradle files which will always come in bulk.

I did try and split it up for you, but it wont reduce the PR size by much and is a lot of work on my side.

**Comment by Daeda88** [comment]
Alternatively you could merge https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/386/files first, and Ill make sure I track the changes

**Comment by nbransby** [comment]
`gradle check` fails on https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/386, does it work on this branch?

**Comment by Daeda88** [comment]
@nbransby there was a merge issue with test-utils. I fixed them, so I expect CI to work now (tests run locally at least)

**Comment by nbransby** [comment]
does `gradle check` pass?

**Comment by Daeda88** [comment]
It does now. There's a bit of a bug/missing feature with Kotlin 1.8 where AndroidUnitTest automatically has a dependency on commonTest. This is problematic because the tests in this library are instrumented tests. Kotlin 1.9 allows the disabling of the dependency, but for now, I solved it by making an Annotation `@IgnoreForAndroidUnitTest` which will make sure the tests are not done for Android Unit tests specifically.

**Comment by nbransby** [comment]
do you have a link to the docs on Kotlin 1.9 allows the disabling of the dependency?

**Comment by Daeda88** [comment]
https://slack-chats.kotlinlang.org/t/8582216/is-it-expected-that-new-androidinstrumentedtest-sourceset-do#481668b4-9d5f-4ef4-b4c4-1fdd05769b37

**Comment by nbransby** [comment]
I noticed `gradle check` doesn't run the android instrumented tests and `gradle connectedCheck` appears to hang...
```
> Task :firebase-firestore:connectedDebugAndroidTest
Starting 36 tests on Pixel 4 - 13
```

Any ideas on that?

**Comment by Daeda88** [comment]
@nbransby sorry I completely forgot to respond at the time. I had to upgrade our tooling to Kotlin 1.9.10 due to build issues with XCode 15 on older kotlin versions, so Ive amended the PR with the latest changes from master.

Re the connected devices, looks like the expected emulator was not there, Ill try and have a look. I can run connectedCheck just fine on my local machine, so its probably some CI configuration.

**Comment by nbransby** [comment]
I noticed you have enabled the ios tests again - if you are keen to get them working I have discovered what is needed - KMP ios tests by default run without entitlements for internet or keychain access

**Comment by Daeda88** [comment]
All but auth ran for me locally. I noticed the same about keychain access, but I havent found a way to set the entitlements for the test runner yet though

**Comment by nbransby** [comment]
I believe its possibly following the advice in these issues:
https://youtrack.jetbrains.com/issue/KT-53129/Cant-dispatch-to-the-main-thread-in-native-tests

**Comment by Daeda88** [comment]
So far I havent been able to fix it with the `sectcreate` linkeropts. Could be an error with the plist but the error message doesnt change so who knows 🤷

**Comment by nbransby** [comment]
You should ask on that thread if you can't figure it out

**Comment by Daeda88** [comment]
@nbransby Yeah tried the Kotlin slack as well. Will update if someone responds with a solution. Im also having issues with JS tests randomly failing.getting a timeout on Firestore tests. As far as I can tell, the tests dont actually take as long, but im not sure. Seems to be related to upgrading to IR mode

**Comment by Daeda88** [comment]
@nbransby looks like CI is finally passing!

**Comment by Qw4z1** [comment]
> Once this is merged, I can make a few more PRs from our Splendo fork, including fixes to Polymorphic serialization (it fails for nesting, doesnt support non-sealed polymorphism etc), several iOS methods, and tracking the new firestore persistence settings

@Daeda88, would any of the fixes you mention include a fix for #420?

**Comment by Qw4z1** [comment]
> > And yeah, its kind of big because the new Android filestructure requires renames from androidAndroidTest to androidInstrumentedTest etc. But the old way will get deprecated so you'll have to do the renames eventually.
> 
> This PR includes upgrading kotlin.mpp.androidSourceSetLayoutVersion to 2? That's great as it was on our todo list but it would be super helpful if that was in the PR title of description somewhere. In fact this task alone would make a sizable PR and should really be submitted separately, that would really help us improve our TTM (time to merge) on this project 🙏

@nbransby, is this todo list that you mention publicly available somewhere? If not, I think it could make it easier for people who wants to contribute to know where they should start. 😇

**Comment by nbransby** [comment]
> @nbransby looks like CI is finally passing!

@Daeda88 I'm guessing the ios tests defeated you in the end 😅

**Comment by Daeda88** [comment]
JS tests actually. They fail randomly and I don't know why. Rerunning ci a bunch of times will eventually pass it.

**Comment by nbransby** [comment]
> @nbransby, is this todo list that you mention publicly available somewhere? If not, I think it could make it easier for people who wants to contribute to know where they should start. 😇

@Qw4z1 yes plenty of places to start here https://github.com/GitLiveApp/firebase-kotlin-sdk/issues

**Comment by Daeda88** [comment]
I'm currently upgrading our internal fork to 1.9.20 and there JS seems to pass fine. Now it's the Android tests XD. Once its stable I'll update this pr again.

**Comment by Daeda88** [comment]
@nbransby upgraded to Kotlin 1.9.20. On our fork this now builds reliable. HOWEVER the Android tests fail on MacOS latest: the auth api is giving some timeouts for the Android emulator. We've resolved it by running on a 4 core ubuntu machine, but that is not free (0,016 USD per minute, at a build time of approximately 7 min). If you know of a way to optimize id be happy to do it, but so far no luck.

**Comment by nbransby** [comment]
Have you got a link to the failed runs?

Are you still running the iOS tests on Mac?

**Comment by Daeda88** [comment]
Here's an example: https://github.com/splendo/firebase-kotlin-sdk/actions/runs/6905089285/job/18787135516
Still running iOS tests, but Ive split Android/iOS/JS over three jobs/machines to increase build time (and make tests better, since it ensures a clean firebase emulator)

**Comment by MattSkala** [comment]
> @nbransby upgraded to Kotlin 1.9.20. On our fork this now builds reliable. HOWEVER the Android tests fail on MacOS latest: the auth api is giving some timeouts for the Android emulator. We've resolved it by running on a 4 core ubuntu machine, but that is not free (0,016 USD per minute, at a build time of approximately 7 min). If you know of a way to optimize id be happy to do it, but so far no luck.

I've tried running the Android tests on the standard ubuntu-latest runner and it seems to work fine: https://github.com/MattSkala/firebase-kotlin-sdk/actions/runs/6989496153/job/19018094669?pr=2

**Comment by nbransby** [comment]
> Still running iOS tests, but Ive split Android/iOS/JS over three jobs/machines to increase build time (and make tests better, since it ensures a clean firebase emulator)

@Daeda88 are we able to do this over free machines with the android tests running on standard ubuntu-latest runner which according to @MattSkala seems to work

**Comment by Daeda88** [comment]
@nbransby @MattSkala Set it to Ubuntu latest and also upgraded to 1.9.21

**Comment by MattSkala** [comment]
> @nbransby @MattSkala Set it to Ubuntu latest and also upgraded to 1.9.21

@Daeda88 I see the workflow failed, it would probably be better to get macOS working after all, can you give it one more shot?

After looking at the workflows, I think there might be a race condition as there is no wait until Firebase Emulator is started. It might happen that tests are started before the emulators are ready. We could wait for the emulator to start in the setup test action e.g. using wait-on: https://github.com/MattSkala/firebase-kotlin-sdk/pull/2/commits/49dc48b18b10cda2202089e6b22a3e797dab0930

**Comment by Daeda88** [comment]
@MattSkala pushed MacOS 13 again. Doubt it works and I dont really see a good way to counter the race condition. Any suggestions?

**Comment by Daeda88** [comment]
@nbransby well waddayouknow, apparently it works fine on MacOS 13 for Kotlin 1.9.21. Merging is obviously blocked due to review & an expected build on api 29 instead of 34 which is latest, but that's nothing I can control :)

**Review by MattSkala — APPROVED** [review]

**Pull request merged**
