### PR TITLE
Run android emulator on ubuntu build agent

### PR DESCRIPTION
**Pull request by siarhei-luskanau**

### CODE REVIEW

**Comment by nbransby** [comment]
@siarhei-luskanau were you hoping this might fix the fakey android tests?

**Comment by Reedyuk** [comment]
Seems to be failing, could you fix it and get it passing. Happy to merge once it passes

**Comment by siarhei-luskanau** [comment]
> @siarhei-luskanau were you hoping this might fix the fakey android tests?

I will try to fix the android tests. Additional I would like to add the [gradle-managed-devices](https://developer.android.com/studio/test/gradle-managed-devices) to project and use it instead of `reactivecircus/android-emulator-runner` GitHub action task

**Comment by Reedyuk** [comment]
ok that makes sense. Use this pr to do those changes and get the tests passing and i will review and get it merged in

**Comment by nbransby** [comment]
Execution failed for task ':firebase-app:gradleManagedDeviceSetup'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.ManagedDeviceInstrumentationTestSetupTask$ManagedDeviceSetupRunnable
   > java.util.concurrent.ExecutionException: com.android.builder.sdk.LicenceNotAcceptedException: Failed to install the following Android SDK packages as some licences have not been accepted.
        system-images;android-33;google_atd;x86_64 Google APIs ATD Intel x86_64 Atom System Image
     To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
     All licenses can be accepted using the sdkmanager command line tool:
     sdkmanager.bat --licenses
     Or, to transfer the license agreements from one workstation to another, see https://developer.android.com/studio/intro/update.html#download-with-gradle
     
     Using Android SDK: /usr/local/lib/android/sdk

**Comment by siarhei-luskanau** [comment]
@Reedyuk @nbransby I managed to split the android tests by modules. Now GitHub Actions launch the build agent for each Gradle module with  android tests.
I still in progress with replacing the `reactivecircus/android-emulator-runner` with the [gradle-managed-devices](https://developer.android.com/studio/test/gradle-managed-devices)

**Comment by Reedyuk** [comment]
> @Reedyuk @nbransby I managed to split the android tests by modules. Now GitHub Actions launch the build agent for each Gradle module with android tests. I still in progress with replacing the `reactivecircus/android-emulator-runner` with the [gradle-managed-devices](https://developer.android.com/studio/test/gradle-managed-devices)

Really nice work, thanks for the contribution.
What is the impact on merging this in now? you can add a new pr for the other change?

**Comment by Reedyuk** [comment]
Ah crashlytics is failing

**Comment by siarhei-luskanau** [comment]
> Ah crashlytics is failing

Right! Crashlytics is failing. Benefit on that PR is splitting tests by module. So other modules is tested successfully.

**Comment by siarhei-luskanau** [comment]
> What is the impact on merging this in now? you can add a new pr for the other change?

This PR contains unused and uncompleted code related he [gradle-managed-devices](https://developer.android.com/studio/test/gradle-managed-devices).
I will continue this in other PR

**Comment by Reedyuk** [comment]
> > Ah crashlytics is failing
> 
> Right! Crashlytics is failing. Benefit on that PR is splitting tests by module. So other modules is tested successfully.

Get a green tick on all and happy to merge this in.

**Comment by siarhei-luskanau** [comment]
@Reedyuk I have applied the [gradle-managed-devices](https://developer.android.com/studio/test/gradle-managed-devices) with api 33 instead of 34. Right now I see emulator failing with api 34

**Review by Reedyuk — APPROVED** [review]

**Comment by siarhei-luskanau** [comment]
@Reedyuk I have added the `devRunEmulatorTests` Gradle task for developers to launch Android tests locally

**Comment by Reedyuk** [comment]
Thank you for your hard work @siarhei-luskanau

**Pull request merged**
