### PR TITLE
Failing sealed class list encoding / decoding tests

### PR DESCRIPTION
**Pull request by brahyam**
Hi!,

Thanks a lot for the huge effort of making available this library. 

While using the SDK to store a list of sealed classes I ran into the following error on decoding.
`NullPointerException: null cannot be cast to non-null type kotlin.collections.Map<*, *>`

I managed to track it to `firebase-common/androidMain/_decoders.kt` `FirebaseDecoder.structureDecoder` function. (and also its iOS equivalent)

It happens because the descriptor is expecting a `value` property that was not encoded. I managed to fix it with the following
```kotlin
StructureKind.CLASS, StructureKind.OBJECT, PolymorphicKind.SEALED -> (value as Map<*, *>).let { map ->
        FirebaseClassDecoder(decodeDouble, map.size, { map.containsKey(it) }) { desc, index ->
            val elementName = desc.getElementName(index)
            if (desc.kind is PolymorphicKind && elementName == "value") {
                map
            } else {
                map[desc.getElementName(index)]
            }
        }
    }
```
And similar for the iOS but maybe there is a more elegant way?

I will open an issue with the same comment and link this PR

### CODE REVIEW

**Comment by Reedyuk** [comment]
Can you fix the build failure please.

**Review by Reedyuk — APPROVED** [review]

**Comment by Reedyuk** [comment]
@nbransby

**Comment by brahyam** [comment]
@Reedyuk @nbransby any chance it could be merged soon? 🙏🏼

**Comment by Reedyuk** [comment]
I approved, it's on @nbransby

**Review by nbransby — CHANGES_REQUESTED** [review]
there should be separate tests for encode and decode that use nativeAssertEquals and nativeMapOf like the existing tests - this is because you should be testing that it encodes/decodes to the format expected by firebase native libraries

**Comment by brahyam** [comment]
@Reedyuk @nbransby I split the encode and decode tests now and I used `nativeAssertEquals` and `nativeMapOf` for the encoding as other tests.

**Review by nbransby — APPROVED** [review]

**Comment by nbransby** [comment]
great stuff!

**Comment by Reedyuk** [comment]
@brahyam - does this work for you locally? the ci is getting stuck on the ios tests,

**Pull request merged**
