### PR TITLE
Firebase Auth: Add createUserWithEmailAndPassword.

### PR DESCRIPTION
**Pull request by vanniktech**
Tested this together with `signInWithEmailAndPassword` on Android & it works.

Dunno if the JS / iOS implementation is correct but looking at a first glance it looks like!

### CODE REVIEW

**Comment by vanniktech** [comment]
Build failure seems unrelated. Master is also red 🤷

**Comment by nbransby** [comment]
Thanks! This looks good, but could you also add a test for it? The CI for the tests is broken at the moment but they can run locally.

**Comment by vanniktech** [comment]
I did but executing `gradle test` yields:

```
> Task :firebase-auth:compileDebugUnitTestKotlinAndroid FAILED
e: /Users/niklas/dev/GitHub/firebase-kotlin-sdk/firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt: (16, 12): Expected property 'context' has no actual declaration in module <firebase-auth_debug> for JVM
e: /Users/niklas/dev/GitHub/firebase-kotlin-sdk/firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt: (17, 12): Expected function 'runTest' has no actual declaration in module <firebase-auth_debug> for JVM

> Task :firebase-auth:compileReleaseUnitTestKotlinAndroid FAILED
e: /Users/niklas/dev/GitHub/firebase-kotlin-sdk/firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt: (16, 12): Expected property 'context' has no actual declaration in module <firebase-auth_release> for JVM
e: /Users/niklas/dev/GitHub/firebase-kotlin-sdk/firebase-auth/src/commonTest/kotlin/dev/gitlive/firebase/auth/auth.kt: (17, 12): Expected function 'runTest' has no actual declaration in module <firebase-auth_release> for JVM
```

Also, is there any way to delete a registered account?

**Comment by nbransby** [comment]
You can run the tests for JS using `allTests` task and for android with `connectedAndroidTest`.

`tests` task tries to run android non-instrumented tests which appear to expect a JVM target - not really sure how to solve that but seems like it might be a kotlin multiplatform bug.

`iosTest` will run the ios tests but they will fail at the moment because of more multiplatform weirdness we haven't solved yet.

**Comment by vanniktech** [comment]
Executed tests locally and this works now @nbransby

**Comment by vanniktech** [comment]
Build failure is unrelated:

```
> Task :firebase-app:linkDebugTestIos FAILED
Please try to disable compiler caches and rerun the build. To disable compiler caches, add the following line to the gradle.properties file in the project's root directory:
    
    kotlin.native.cacheKind=none
    
Also, consider filing an issue with full Gradle log here: https://kotl.in/issue
The /Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: framework not found FirebaseCore

FAILURE: Build failed with an exception.
7 actionable tasks: 7 executed

* What went wrong:
Execution failed for task ':firebase-app:linkDebugTestIos'.
> Compilation finished with errors
```

**Pull request merged**
